---
- name: Update Jenkins on Ubuntu
  hosts: all
  become: yes

  tasks:

  - name: Find existing Jenkins WAR file
    shell: "find / -type f -name jenkins.war 2>/dev/null"
    register: jenkins_war_locations
    ignore_errors: yes

  - name: Download latest Jenkins WAR file
    get_url:
      url: https://updates.jenkins.io/download/war/2.440.1/jenkins.war
      dest: /tmp/jenkins.war
      force: yes

  - name: Stop Jenkins service
    service:
     name: jenkins
     state: stopped

  - name: Transfer Jenkins WAR file to remote host
    synchronize:
      src: "/tmp/jenkins.war"
      dest: "/tmp/jenkins.war"
      mode: pull

  - name: Copy new Jenkins WAR file to all locations
    copy:
      src: "/tmp/jenkins.war"
      dest: "{{ item }}"
    loop: "{{ jenkins_war_locations.stdout_lines }}"
    when: jenkins_war_locations.stdout != ""

  - name: Start Jenkins service  
    service:
      name: jenkins
      state: started
