---
- hosts: all
  become: yes

  vars:
    user_name: myuser
    new_password: "mysecurepassword"

  tasks:

    - name: Update user password
      user:
        name: "{{ user_name }}"
        password: "{{ new_password | password_hash('sha512') }}"
        update_password: always