# user-management.yml
- hosts: all
  become: yes

  tasks:
    - name: Get list of active users
      shell: "awk -F: '($3>=1000) && ($1!=\"nobody\") {print $1}' /etc/passwd"
      register: active_users
      changed_when: false

    - name: Check if user is in sudo group
      command: "groups {{ item }} | grep -q sudo"
      loop: "{{ active_users.stdout_lines }}"
      register: sudo_users
      changed_when: false
      failed_when: false

    - name: Display active users
      debug:
        msg: "Active users:"

    - name: Display sudo users
      debug:
        msg: "{{ item.item }} (sudo)"
      loop: "{{ sudo_users.results }}"
      when: item.rc == 0

    - name: Display standard users
      debug:
        msg: "{{ item }}"
      loop: "{{ active_users.stdout_lines }}"
      when: not item in sudo_users.results|map(attribute='item')|list

  vars:
    ansible_python_interpreter: /usr/bin/python3